### ISSUE TITLE
Request for the code to run ToT on GSM8k, AQuA, and StrategyQA Datasets

### ISSUE THREAD

**Issue by twni2016** [maitrix-org/llm-reasoners#105]
Hi authors,

I’d like to run ToT (BFS/DFS) on the GSM8k dataset to reproduce the results shown in Table 3. However, I couldn’t find the code for GSM8k, AQuA, or StrategyQA in the `examples/ToT` folder.

Could you please point me to the relevant code for these datasets? Thank you!

**Comment by Ber666** [comment]
Hi,

Thanks for your interest in our project.

We looked through our git log, but it seems that the scripts for these experiments might not have been fully merged, and we may have lost track of them in the process... We apologize for any inconvenience this may cause.
