### ISSUE TITLE
React HotpotQA

### ISSUE THREAD

**Issue by AU-CPU** [maitrix-org/llm-reasoners#110]
CUDA_VISIBLE_DEVICES=0 python3 -m torch.distributed.run --nproc_per_node 1 examples/ReAct/hotpotqa/inference.py --base_lm llama3 --model_dir /xx/llama3-8b/ --llama_size "8B" --batch_size 1 --temperature 0
Unable to run inference.py correctly.

   reasoner = Reasoner(
        world_model=HotpotqaWorldModel(world_base_model,toolset),
        search_config=HotpotqaSearchConfig(base_model),
        search_algo=GreedySearch(7)
    )
TypeError: Hotpotqaevaluator.__init__() missing 1 required positional argument: 'toolset'
It seems that the reason for the lack of definition of toolset here is that I did not find the definition of toolset in inference. I hope to get a reply.

**Comment by AU-CPU** [comment]
@xiyan128 @ZhitingHu

**Comment by Yanbin-Yin** [comment]
line6: from reasoners.tools import wikisearch,wikilookup,wikifinish

In this example we just use these three tools. And you can just use these tools to define a toolset.

**Comment by AU-CPU** [comment]
I use from reasoners.tools import wikisearch,wikilookup,wikifinish
 and change code to "
if "Search" in action:
                new_state = current_state + self.toolset[0](env=self.base_model, step_idx=step_idx, action=action, thought=thought)
                # new_state = current_state + HotpotQATools.wikisearch(env=self.base_model, step_idx=step_idx, action=action, thought=thought)
                print("Search tool is used")
            elif "Lookup" in action:
                new_state = current_state + self.toolset[0](env=self.base_model, step_idx=step_idx, action=action, thought=thought)
                # new_state = current_state + HotpotQATools.wikilookup(env=self.base_model, step_idx=step_idx, action=action, thought=thought)
                print("Lookup tool is used")
            elif "Finish" in action:
                new_state = current_state + self.toolset[0](env=self.base_model, step_idx=step_idx, action=action, thought=thought)
                # new_state = current_state + HotpotQATools.wikifinish(env=self.base_model, step_idx=step_idx, action=action, thought=thought)
                print("Finish tool is used")"
it can be run, but the acc=0
[](url)

**Comment by AU-CPU** [comment]
Case #7400: correct=False, output=None, answer='Ouse and Foss';accuracy=0.000 (0/7400)                                                                    
hotpotqa: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊| 7396/7405 [02:01<00:00, 56.01it/s]----------------------------------------
----------------------------------------
Case #7401: correct=False, output=None, answer='Yasir Hussain';accuracy=0.000 (0/7401)                                                                    
hotpotqa: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊| 7396/7405 [02:01<00:00, 56.01it/s]----------------------------------------
----------------------------------------
Case #7402: correct=False, output=None, answer='no';accuracy=0.000 (0/7402)                                                                               
hotpotqa: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████▊| 7396/7405 [02:01<00:00, 56.01it/s]----------------------------------------
----------------------------------------
Case #7403: correct=False, output=None, answer='yes';accuracy=0.000 (0/7403)                                                                              
hotpotqa: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉| 7403/7405 [02:01<00:00, 58.09it/s]----------------------------------------
----------------------------------------
Case #7404: correct=False, output=None, answer='yes';accuracy=0.000 (0/7404)                                                                              
hotpotqa: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████▉| 7403/7405 [02:01<00:00, 58.09it/s]----------------------------------------
----------------------------------------
Case #7405: correct=False, output=None, answer='Norwood, Massachusetts';accuracy=0.000 (0/7405)                                                           
hotpotqa: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████| 7405/7405 [02:01<00:00, 60.85it/s]
0.0

**Comment by Yanbin-Yin** [comment]
You can print "new_state" and "current_state" to find whether these tools are used.

**Comment by AU-CPU** [comment]
It looks like it has not entered step(self, state, action).Where can I solve this error?
