### ISSUE TITLE
tot game24 reproduce error

### ISSUE THREAD

**Issue by 0Frett** [maitrix-org/llm-reasoners#65]
Hi I am trying to reproduce tot game24 using beam search and i found out that sometimes even if model get 24 sucessfully, we still can get correct=False because the output=None. How to fix it? I run this search on question 900.

following is my search config:
model: gpt-turbo-3.5
beam_size: 5
max_depth: 4
sampling_strategy: argmax
replace: None
temperature: None
temperature_decay: None
reject_sample: None
reject_min_reward: None
unbiased: None
reward_aggregator: last
action_dedup: False
early_terminate: True
return_beam: False

![correct](https://github.com/maitrix-org/llm-reasoners/assets/116897066/95794518-1fd2-4ac9-8232-6484d73d52ce)
![incorrect](https://github.com/maitrix-org/llm-reasoners/assets/116897066/0073ed4e-a5f1-4108-8d97-95180517d77f)
![incorrect2](https://github.com/maitrix-org/llm-reasoners/assets/116897066/3f7ed349-6731-4b61-a9e8-7e3b70a5302c)

**Comment by Ber666** [comment]
Hi, there was a bug of beam search, which we fixed at this [commit](https://github.com/maitrix-org/llm-reasoners/commit/6040de0513310734f28834829b2ae02d9155972b). Could you try again now?

**Comment by 0Frett** [comment]
i think the bug is fixed! Thanks a lot.
