### ISSUE TITLE
You forgot to change the path of some datasets.

### ISSUE THREAD

**Issue by chenhengzh** [maitrix-org/llm-reasoners#78]
There are some examples:

~/reasoners/benchmark/aqua.py
<img width="740" alt="image" src="https://github.com/maitrix-org/llm-reasoners/assets/74190205/9ea058f7-80f3-4877-93c8-01d769ec8192">

~/examples/RAP/gsm8k
<img width="1054" alt="image" src="https://github.com/maitrix-org/llm-reasoners/assets/74190205/f2fb5e07-0c83-4e32-8b81-2669f2dcdfa8">

You may need to recheck these paths.

**Comment by Ber666** [comment]
Thanks. We've fixed this problem
