### ISSUE TITLE
MCTS/Tree of Thought for HotpotQA

### ISSUE THREAD

**Issue by RishabhMaheshwary** [maitrix-org/llm-reasoners#98]
Hello! I saw an example of ReAct on HotpotQA benchmark. Does `llm-reasoners` support tree based search for HotpotQA task? Thanks!

**Comment by Ber666** [comment]
Hi! We currently don't have a ready-to-run example of tree search specifically for the HotpotQA task. However, our library should be helpful to implement this (e.g., there are several tree search algorithms you could use). The key component that might be missing is a reward function to guide the search, which you'll likely need to define based on your needs. Let me know if you need further details!

**Comment by RishabhMaheshwary** [comment]
Thanks for the directions!
